### ISSUE TITLE
TS01 - Método para esconder o Token

### ISSUE THREAD

**Issue by filipetoyoshima** [TecProg-20181/T--yesterday_you_said_tomorrow#1]
O Token do Bot deve ser retirado do arquivo principal e ser colocado em um arquivo que não será upado para o repositório remoto.

## Critérios de aceitação:
- [ ] .gitignore com o nome do arquivo

**Comment by cjjcastro** [comment]
Foi resolvido pelo grupo que não usaremos um arquivo para salvar o token mas sim uma variável de ambiente. Para criar a variável basta executar o comando a seguir inserindo o token desejado.
> export BOT_API_TOKEN="<aqui vai o token gerado pelo botfather>"

**Comment by filipetoyoshima** [comment]
A solução parece adequada à problemática. O levantamento de critérios foi errôneo.
