### ISSUE TITLE
TS07 - Accept list of IDs to any operation that use ID as parameter

### ISSUE THREAD

**Issue by Hiroshi18** [TecProg-20181/T--yesterday_you_said_tomorrow#24]
The bot must accept many IDs as parameters to the following operations:
## Acceptance Criteria
- [x] Todo
- [x] Doing
- [x] Done
- [x] Delete
- [x] Duplicate
- [x] Priority (first argument after command must be the priority)
- [x] Duedate (first argument after command must be the due date)

**Comment by cjjcastro** [comment]
description please
