### ISSUE TITLE
TS02 - Remove Possibility Of Circular Dependency

### ISSUE THREAD

**Issue by filipetoyoshima** [TecProg-20181/T--yesterday_you_said_tomorrow#3]
Dependência Circular ocorre quando uma tarefa A depende de uma tarefa B que, em alguma instância, vem a depender da tarefa A, causando assim um deadlock e impossibilitando a realização de qualquer uma das tarefas envolvidas.
## Critérios de Aceitação
- [x] Dependência Circular deve ser impedida pelo algorítmo
- [x] Ao tentar criar uma dependência, o usuário deve ser informado de quais tarefas causariam o deadlock

**Comment by cjjcastro** [comment]
Dependência circular não é mais permitido pelo código.
